---
- hosts: localhost
  tasks:
  - name: "line in file"
    lineinfile:
      path: /tmp/my.conf
      regexp: '(.*)456(.*)'
      state: absent 
    register: conf
    check_mode: yes
#    register: conf
#    failed_when: (conf is changed) or (conf is failed)

  - debug: msg="{{conf}}"


<<<<<<< HEAD
#line is required with state=present

#Arrays passed as arguments
#--extra-vars {KeyToUpdate:[${KeysToUpdate}]}
=======
#line is required with state=present
>>>>>>> 1b9ded649a99f6640ad8ebf9349da3fbfa5fb7c4
